"""
This type stub file was generated by pyright.
"""

import sys

"""
Compatibility tools for differences between Python 2 and 3
"""
PY37 = ...
asunicode = ...
__all__ = ["asunicode", "asstr", "asbytes", "Literal", "lmap", "lzip", "lrange", "lfilter", "with_metaclass"]
def asbytes(s): # -> bytes:
    ...

def asstr(s): # -> str:
    ...

def lrange(*args, **kwargs): # -> list[int]:
    ...

def lzip(*args, **kwargs): # -> list[tuple[Any, ...]]:
    ...

def lmap(*args, **kwargs): # -> list[Any]:
    ...

def lfilter(*args, **kwargs): # -> list[Any]:
    ...

def with_metaclass(meta, *bases): # -> metaclass:
    """Create a base class with a metaclass."""
    class metaclass(meta):
        ...
    
    

if sys.version_info >= (3, 8):
    ...
else:
    ...
