"""
This type stub file was generated by pyright.
"""

from .qsturng_ import p_keys, psturng, qsturng, v_keys
from statsmodels.tools._testing import PytestTester

__all__ = ['p_keys', 'psturng', 'qsturng', 'v_keys', 'test']
test = ...
