"""
This type stub file was generated by pyright.
"""

from xgboost.callback import TrainingCallback as XGBTrainingCallback

class XGBPlottingCallback(XGBTrainingCallback):
    '''XGBoost callback with metrics plotting widget from CatBoost
    '''
    def __init__(self, total_iterations: int) -> None:
        ...
    
    def after_iteration(self, model, epoch, evals_log): # -> Literal[False]:
        ...
    


def lgbm_plotting_callback(): # -> Callable[..., None]:
    """LightGBM callback with metrics plotting widget from CatBoost
    """
    ...

