"""
This type stub file was generated by pyright.
"""

import typing as tp
from typing import Any, List, Optional, Union
from .ipythonwidget import MetricWidget

logger = ...
class MetricsWidget(MetricWidget):
    def __init__(self) -> None:
        ...
    
    def update_data(self, data: tp.Dict) -> None:
        ...
    


class MetricsPlotter:
    """
    Context manager that enables widget with learning curves in
    JupyterLab / Jupyter Notebook
    """
    def __init__(self, train_metrics: List[Union[str, tp.Dict[str, str]]], test_metrics: Optional[List[Union[str, tp.Dict[str, str]]]] = ..., total_iterations: Optional[int] = ...) -> None:
        """
        Constructor that defines metrics to be plotted and total iterations count.

        Parameters
        ----------
        train_metrics : list of str or list of dict
            List of train metrics to be tracked.
            Each item in list can be either string with metric name or dict
            with the following format:
            {
                "name": "{metric_name}",
                "best_value": "Max|Min|Undefined",
            }

        test_metrics : list of str or list of dict, optional (default=None)
            List of test metrics to be tracked.
            Has the same format as train_metrics. Equals to train_metrics, if not defined

        total_iterations: int, optional (default=None)
            Total number of iterations, allows for remaining time estimation.
        """
        ...
    
    def __enter__(self) -> MetricsPlotter:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback) -> Any:
        ...
    
    @staticmethod
    def construct_metrics_meta(metrics: List[Union[str, tp.Dict[str, str]]]) -> List[tp.Dict[str, str]]:
        ...
    
    @staticmethod
    def construct_metrics_array(metrics_positions: tp.Dict[str, int], metrics: tp.Dict[str, float]) -> List[float]:
        ...
    
    def estimate_remaining_time(self, time_from_start: float) -> Optional[float]:
        ...
    
    def log(self, epoch: int, train: bool, metrics: tp.Dict[str, float]) -> None:
        """
        Save metrics at specific training epoch.

        Parameters
        ----------
        epoch : int
            Current epoch

        train : bool
            Flag that indicates whether metrics are calculated on train or test data

        metrics: dict
            Values for each of metrics defined in `__init__` method of this class
        """
        ...
    


