"""
This type stub file was generated by pyright.
"""

from .formulatools import handle_formula_data
from statsmodels.tools._testing import PytestTester

__all__ = ['handle_formula_data', 'test']
test = ...
