"""
This type stub file was generated by pyright.
"""

"""Anova k-sample comparison without and with trimming

Created on Sun Jun 09 23:51:34 2013

Author: Josef Perktold
"""
def trimboth(a, proportiontocut, axis=...): # -> ndarray[Any, dtype[Any]]:
    """
    Slices off a proportion of items from both ends of an array.

    Slices off the passed proportion of items from both ends of the passed
    array (i.e., with `proportiontocut` = 0.1, slices leftmost 10% **and**
    rightmost 10% of scores).  You must pre-sort the array if you want
    'proper' trimming.  Slices off less if proportion results in a
    non-integer slice index (i.e., conservatively slices off
    `proportiontocut`).

    Parameters
    ----------
    a : array_like
        Data to trim.
    proportiontocut : float or int
        Proportion of total data set to trim of each end.
    axis : int or None
        Axis along which the observations are trimmed. The default is to trim
        along axis=0. If axis is None then the array will be flattened before
        trimming.

    Returns
    -------
    out : ndarray
        Trimmed version of array `a`.

    Examples
    --------
    >>> from scipy import stats
    >>> a = np.arange(20)
    >>> b = stats.trimboth(a, 0.1)
    >>> b.shape
    (16,)

    """
    ...

def trim_mean(a, proportiontocut, axis=...): # -> Any:
    """
    Return mean of array after trimming observations from both lower and upper
    tails.

    If `proportiontocut` = 0.1, slices off 'leftmost' and 'rightmost' 10% of
    scores. Slices off LESS if proportion results in a non-integer slice
    index (i.e., conservatively slices off `proportiontocut` ).

    Parameters
    ----------
    a : array_like
        Input array
    proportiontocut : float
        Fraction to cut off of both tails of the observations
    axis : int or None
        Axis along which the trimmed means are computed. The default is axis=0.
        If axis is None then the trimmed mean will be computed for the
        flattened array.

    Returns
    -------
    trim_mean : ndarray
        Mean of trimmed array.

    """
    ...

class TrimmedMean:
    """
    class for trimmed and winsorized one sample statistics

    axis is None, i.e. ravelling, is not supported
    """
    def __init__(self, data, fraction, is_sorted=..., axis=...) -> None:
        ...
    
    @property
    def data_trimmed(self):
        ...
    
    @property
    def data_winsorized(self): # -> NDArray[Any]:
        """winsorized data
        """
        ...
    
    @property
    def mean_trimmed(self): # -> Any:
        """mean of trimmed data
        """
        ...
    
    @property
    def mean_winsorized(self): # -> Any:
        """mean of winsorized data
        """
        ...
    
    @property
    def var_winsorized(self): # -> Any:
        """variance of winsorized data
        """
        ...
    
    @property
    def std_mean_trimmed(self): # -> Any:
        """standard error of trimmed mean
        """
        ...
    
    @property
    def std_mean_winsorized(self): # -> Any:
        """standard error of winsorized mean
        """
        ...
    
    def ttest_mean(self, value=..., transform=..., alternative=...): # -> tuple[Any, NDArray[signedinteger[Any]] | ndarray[Any, dtype[Any]], Any]:
        """
        One sample ttest for trimmed or Winsorized mean

        Parameters
        ----------
        value : float
            Value of the mean under the Null hypothesis
        transform : {'trimmed', 'winsorized'}
            Specified whether the mean test is based on trimmed or winsorized
            data.
        alternative : {'two-sided', 'larger', 'smaller'}


        Notes
        -----
        p-value is based on the approximate t-distribution of the test
        statistic. The approximation is valid if the underlying distribution
        is symmetric.
        """
        ...
    
    def reset_fraction(self, frac): # -> TrimmedMean:
        """create a TrimmedMean instance with a new trimming fraction

        This reuses the sorted array from the current instance.
        """
        ...
    


def scale_transform(data, center=..., transform=..., trim_frac=..., axis=...): # -> NDArray[Any] | Any:
    """Transform data for variance comparison for Levene type tests

    Parameters
    ----------
    data : array_like
        Observations for the data.
    center : "median", "mean", "trimmed" or float
        Statistic used for centering observations. If a float, then this
        value is used to center. Default is median.
    transform : 'abs', 'square', 'identity' or a callable
        The transform for the centered data.
    trim_frac : float in [0, 0.5)
        Fraction of observations that are trimmed on each side of the sorted
        observations. This is only used if center is `trimmed`.
    axis : int
        Axis along which the data are transformed when centering.

    Returns
    -------
    res : ndarray
        transformed data in the same shape as the original data.

    """
    ...

