"""
This type stub file was generated by pyright.
"""

fspath = ...
def try_plot_offline(figs): # -> None:
    ...

def save_plot_file(plot_file, plot_name, figs): # -> None:
    ...

class OfflineMetricVisualizer:
    def __init__(self, train_dirs) -> None:
        ...
    
    def save_to_file(self, title, file_output): # -> None:
        ...
    


