"""
This type stub file was generated by pyright.
"""

import warnings
from statsmodels._version import __version__, __version_tuple__

debug_warnings = ...
if debug_warnings:
    ...
def test(extra_args=..., exit=...): # -> None:
    """
    Run the test suite

    Parameters
    ----------
    extra_args : list[str]
        List of argument to pass to pytest when running the test suite. The
        default is ['--tb=short', '--disable-pytest-warnings'].
    exit : bool
        Flag indicating whether the test runner should exist when finished.

    Returns
    -------
    int
        The status code from the test run if exit is False.
    """
    ...

__all__ = ["__version__", "__version_tuple__", "test"]
