"""
This type stub file was generated by pyright.
"""

__all__ = ["BayesGaussMI", "BinomialBayesMixedGLM", "Factor", "GEE", "GLM", "GLMGam", "GLS", "GLSAR", "GeneralizedPoisson", "Logit", "MANOVA", "MI", "MICE", "MICEData", "MNLogit", "MixedLM", "NegativeBinomial", "NegativeBinomialP", "NominalGEE", "OLS", "OrdinalGEE", "PCA", "PHReg", "Poisson", "PoissonBayesMixedGLM", "ProbPlot", "Probit", "QuantReg", "RLM", "RecursiveLS", "SurvfuncRight", "WLS", "ZeroInflatedGeneralizedPoisson", "ZeroInflatedNegativeBinomialP", "ZeroInflatedPoisson", "__version__", "__version_tuple__", "add_constant", "categorical", "cov_struct", "datasets", "distributions", "duration", "emplike", "families", "formula", "gam", "genmod", "graphics", "iolib", "load", "load_pickle", "multivariate", "nonparametric", "qqline", "qqplot", "qqplot_2samples", "regression", "robust", "show_versions", "stats", "test", "tools", "tsa", "webdoc"]
load = ...
